# Generated by Django 5.2.5 on 2025-09-03 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_notification_author_purchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancedata',
            options={'ordering': ['-date_uploaded'], 'verbose_name': 'Данные эффективности', 'verbose_name_plural': 'Данные эффективности'},
        ),
        migrations.AddField(
            model_name='performancedata',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('daily', 'Ежедневное'), ('weekly', 'Еженедельное'), ('one_time', 'Разовое')], default='daily', max_length=20, verbose_name='Тип задания'),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработан'),
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('stars_awarded', models.PositiveIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Выполнение задания',
                'verbose_name_plural': 'Выполненные задания',
            },
        ),
    ]
